name: testrunflutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  mailer: ^6.0.0
  http: ^1.4.0
  cloud_firestore: ^5.6.10
  smooth_page_indicator: ^1.2.1
  google_maps_flutter: ^2.10.1
  geolocator:
    git:
      url: https://github.com/dinhlan1234/flutter-geolocator.git
      ref: main
      path: geolocator
  flutter_dash: ^1.0.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  equatable: ^2.0.7
  flutter_local_notifications: ^19.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  vietnam_provinces: ^1.0.2
  image: ^4.5.4
  url_launcher: ^6.3.2
  firebase_messaging: ^15.2.10
  googleapis_auth: ^2.0.0
  crypto: ^3.0.6
  path: ^1.9.1
  pointycastle: ^4.0.0
  dart_jsonwebtoken: ^3.2.0
  loading_animation_widget: ^1.3.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_screenutil: ^5.9.3
  pin_code_fields: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO GOBAR VERTICAL 1.png
    - assets/images/welcome1.png
    - assets/images/welcome2.png
    - assets/images/welcome3.png
    - assets/images/login.png
    - assets/images/avtMacDinh.jpg
    - assets/images/barber2.png
    - assets/images/barber1.png
    - assets/images/Barber3.png
    - assets/images/bom.jpg
    - assets/icons/fillter_icon_barberbooking.png
    - assets/icons/setIcon.png
    - assets/images/success3.png
    - assets/logos/logov1.png
    - assets/level/medal.png
    - assets/notification/notification.mp3
    - assets/level/sliver.png
    - assets/level/gold.png
    - assets/level/diamond.png
    - assets/icons/questionDiscord.png
    - assets/icons/homeBottom.png
    - assets/icons/profileBottom.png
    - assets/icons/calendarBottom2.png
    - assets/icons/cahtBottom2.png
    - assets/appsales-a042c-firebase-adminsdk-fbsvc-ae3e9d08c8.json
    - env/.env
